language: php
php:
    - 7
    - 5.6
    - 5.5
    - 5.4

# Enable services to test different drivers
services:
    - redis

# Install dependencies
install:
    - composer install

# Run tests
script:
    - phpunit

# Only build master branch
branches:
    only:
        - master

# Disable notifications
notifications:
      email: false
